### ISSUE TITLE
Лишние либы

### ISSUE THREAD

**Issue by nahy** [57uff3r/nodejs-vksdk#16]
Не уверен, но вроде либы тестовые в node_modules должны быть заигнорены в гите. Смысла нет их держать в хранилище.

**Comment by 57uff3r** [comment]
Да, надо бы подчистить.  Сделаю на досуге.
Ну, или вы сделайте, вольем правки в репо :)

**Comment by phpprog** [comment]
Да будет так! )
https://github.com/57uff3r/nodejs-vksdk/pull/22

**Comment by 57uff3r** [comment]
Спасибище!
Смерджено :+1:
