### ISSUE TITLE
Обновить npm-пакет

### ISSUE THREAD

**Issue by dpolyakov** [57uff3r/nodejs-vksdk#17]
Сейчас есть сделать `npm install vkapi` приведет старая версия с прошлогодичными правками, кажется примерно на эту ревизию 2b9192ab3e8434d4911176f5061860ca5df72c01.
Это очень грустно, апни версию пакета пожалуйста.

**Comment by 57uff3r** [comment]
Мой код ставится через `npm install vksdk` и об этом написано в доке, пакет `vkapi` принадлежит непонятно кому.
