### ISSUE TITLE
Fix docs example at nodejs module site

### ISSUE THREAD

**Issue by LightVolk** [57uff3r/nodejs-vksdk#29]
https://www.npmjs.com/package/vkapi#nodejs-vksdk

docs out of date:

**Comment by LightVolk** [comment]
var vk = new VK({
    'appID'     : 2807970,
    'appSecret' : 'L1ZKpgQPalJdumI6vFK',
    'mode'      : 'oauth'
});

appID shoud be rename to appId

**Comment by 57uff3r** [comment]
This repository is packed to `vksdk` package, `vkapi` package belongs to someone else.
